### ISSUE TITLE
Empty

### ISSUE THREAD

**Issue by kyle-abruzzo** [RealAscarre/UE4-Dumper#2]
well, the Actors Dump, i stoped it at 3gb file size, didn't opened yet, 
the Name dump it's empty
The Objects dump it's like this:
[0x0]:
Name: None
Class: None
ObjectPtr: 0xd16cb9f760
ClassPtr: 0x0

[0x1]:
Name: None
Class: None
ObjectPtr: 0xd16cb9f840
ClassPtr: 0x0

[0x2]:
Name: None
Class: None
ObjectPtr: 0xd16cb9f840
ClassPtr: 0x0

[0x3]:
Name: None
Class: None
ObjectPtr: 0xd16cb9f840
ClassPtr: 0x0

[0x4]:
Name: None
Class: None
ObjectPtr: 0xd16cb9f840
ClassPtr: 0x0

[0x5]:
Name: None
Class: None
ObjectPtr: 0xd16cb9f840
ClassPtr: 0x0

[0x6]:
Name: None
Class: None
ObjectPtr: 0xd16cb9f840
ClassPtr: 0x0

the sdk and sdkw are empty, why?
Game: The Outlast Trials

**Comment by AscarreX** [comment]
Check your offsets once again and try. The dumper offsets can be different from game to game.
